version: '3'

services:
  flask_app:
    restart: always
    build: ./src
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
